# Generated by Django 6.0.2 on 2026-02-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('side', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_id', models.CharField(max_length=30)),
            ],
        ),
    ]
